# Generated by Django 5.2.6 on 2025-11-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CohortWaitList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('interested_course', models.CharField(max_length=225)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
