# Generated by Django 5.2.6 on 2025-12-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tequantweb', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
