# Generated by Django 5.2.6 on 2026-01-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_full_name_enrollment_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='phone_number',
        ),
    ]
