# Generated by Django 5.2.6 on 2025-12-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_module_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(default='no bio yet'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.CharField(default='no pic yet', max_length=225),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
