# Generated by Django 5.2.6 on 2026-01-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_view_students',
            field=models.BooleanField(default=False),
        ),
    ]
