# Generated by Django 5.2.6 on 2026-01-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_enrollment_student_student_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
