# Generated by Django 5.2.6 on 2026-01-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_student_login_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='login_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
